must = _{ SOI ~ "\n"* ~ (comment ~ "\n"+)* ~ (task ~ "\n"+ ~ (comment ~ "\n"+)*)* ~ task? ~ EOI }
task = { target ~ ":" ~ dependent* ~ comment? ~ ("\n" ~ steps)? }
steps = _{ step ~ (NEWLINE ~ step)* }
step = _{ ("\t" | " ")+ ~ action ~ comment? }
dependent = { " " ~ target ~ comment? }
action = { (!("#" | NEWLINE) ~ ANY)+ }
target = { (ASCII_ALPHANUMERIC | "/" | "_" | "-")+ }
comment = _{ " "? ~ "#" ~ (!NEWLINE ~ ANY)* }
